# Generated by Django 2.1.4 on 2018-12-24 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.IntegerField()),
                ('left', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('binary_url', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'Coordinates',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=255)),
                ('is_script', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelfmark', models.CharField(max_length=250, unique=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('page', models.CharField(blank=True, max_length=255, null=True)),
                ('folio', models.CharField(blank=True, max_length=255, null=True)),
                ('scribe', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('catalogue', models.CharField(blank=True, max_length=255, null=True)),
                ('resolution', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('manifest', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='scripts.Manuscript')),
            ],
        ),
        migrations.AddField(
            model_name='coordinates',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='scripts.Letter'),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='scripts.Page'),
        ),
    ]
