# Generated by Django 2.2 on 2019-05-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0003_manuscript_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='slug',
            field=models.SlugField(allow_unicode=True, null=True),
        ),
    ]
