# Generated by Django 2.2 on 2019-05-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_manually_populate_ms_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
