# Generated by Django 2.2 on 2019-05-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0006_auto_20190507_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='manuscript_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
