# Generated by Django 2.2 on 2019-05-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0008_manually_populate_coordinates_msid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='manuscript_id',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddIndex(
            model_name='coordinates',
            index=models.Index(fields=['letter', 'manuscript_id'], name='scripts_coo_letter__c669f3_idx'),
        ),

    ]
