# Generated by Django 2.2 on 2019-05-09 18:30

from django.db import migrations, models
import scripts.priority_field


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0009_add_index_and_notnull_for_coordinates_msid_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='priority',
            field=scripts.priority_field.PriorityField(default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='coordinates',
            index=models.Index(fields=['priority'], name='scripts_coo_priorit_4fe477_idx'),
        ),
    ]
