version: 2
jobs:
  run_tests:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7.2
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Setting permissions
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            pipenv sync
            pipenv install flake8 codecov coverage
            pipenv run python manage.py migrate
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: Run tests
          command: |
            pipenv run coverage run manage.py test
      - run:
          name: Run linting and metrics
          command: |
            pipenv run flake8 ./ tests --output-file test-results
            pipenv run codecov
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1

  deploy_to_prod:
    docker:
      - image: circleci/python:3.7.2
    working_directory: ~
    steps:
      - run:
          name: Install LFTP and deploy
          command: |
            sudo apt-get update
            sudo apt-get install lftp
            touch deploy.txt
            # sftp $FTP_USER:$FTP_PASS@$FTP_HOST:$FTP_PATH <<< $'put deploy.txt'
            lftp -u $FTP_USER,$FTP_PASS -e "set ftp:ssl-allow no;put deploy.txt;quit" $FTP_HOST:$FTP_PATH

workflows:
  version: 2
  run_tests:
    jobs:
      - run_tests:
          filters:
            branches:
              ignore:
                - devel
                - master

  deploy_master_to_prod:
    jobs:
      - run_tests:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - deploy_to_prod:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
