version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7.2
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: test
    steps:
      - checkout
      - run:
          name: Setting permissions
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv install psycopg2 flake8 codecov coverage
            pipenv run python manage.py migrate
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
      - run:
          name: Run tests
          command: |
            pipenv run coverage run manage.py test
      - run:
          name: Run linting and metrics
          command: |
            pipenv run flake8 ./ tests --output-file test-results
            pipenv run codecov
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
